[package]
name = "hailstorm"
version = "0.1.0"
edition = "2021"
authors = ["Davide Ghilardi <dghila@d71.dev>"]
description = "Load testing framework"
keywords = [ "loadtesting", "framework", "tool", "load", "performance" ]
repository = "https://github.com/dghilardi/hailstorm"
license = "MIT"
readme = "README.md"

[dependencies]
tonic = "0.7.2"
prost = "0.10.3"
prost-types = "0.10.1"

[build-dependencies]
tonic-build = "0.7.2"