name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
      
env:
  CARGO_TERM_COLOR: always
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
    
    - name: Run tests
      run: cargo test --verbose
